import { defineConfig } from 'astro/config';
import tailwindcss from '@tailwindcss/vite';
import rehypeSlug from 'rehype-slug';
import rehypeAutolinkHeadings from 'rehype-autolink-headings';
import mdx from '@astrojs/mdx';
import sitemap from '@astrojs/sitemap';

const BASE = '/docs/';

/** Provides a no-op stub for /pagefind/pagefind.js in the dev server.
 *  The real module is generated by `pagefind --site dist` after a production build. */
const pagefindStub = {
    name: 'pagefind-dev-stub',
    apply: /** @type {const} */ ('serve'),
    resolveId(id) {
        if (id === `${BASE}/pagefind/pagefind.js`) return id;
    },
    load(id) {
        if (id === `${BASE}/pagefind/pagefind.js`) {
            return `export async function init() {}
export async function search() { return { results: [] }; }`;
        }
    },
};

// https://astro.build/config
export default defineConfig({
    site: 'https://git.kong.ly',
    base: BASE,
    trailingSlash: 'never',
    vite: {
        plugins: [tailwindcss(), pagefindStub],
        build: {
            rollupOptions: {
                external: [`${BASE}/pagefind/pagefind.js`],
            },
        },
    },
    markdown: {
        rehypePlugins: [
            rehypeSlug,
            [
                rehypeAutolinkHeadings,
                {
                    behavior: 'append',
                    properties: {
                        'aria-label': 'Link to section',
                        class: 'anchor-link',
                    },
                    content: { type: 'text', value: ' #' },
                },
            ],
        ],
        shikiConfig: {
            themes: {
                light: 'github-light',
                dark: 'github-dark-dimmed',
            },
        },
    },
    integrations: [mdx(), sitemap()],
});
